# Generated by Django 4.2.5 on 2023-10-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estate',
            old_name='estatename',
            new_name='housename',
        ),
        migrations.AlterField(
            model_name='estate',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
