# Generated by Django 4.2.5 on 2023-10-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_rename_estatename_estate_housename_alter_estate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='estate',
            name='features',
            field=models.CharField(max_length=200),
        ),
    ]
