# Generated by Django 4.2.5 on 2023-10-05 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_alter_estate_description_alter_estate_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='housename',
        ),
    ]
